cad_enderecos/cad_enderecos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('sys_endereco/', include('sys_endereco.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/sys_endereco/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cad_enderecos/sys_endereco/urls.py
from django.urls import path
from sys_endereco import views


urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='cadastro'),
]

cad_enderecos/sys_endereco/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Endereco(models.Model):
    cep = models.CharField(primary_key=True, max_length=8)
    logradouro = models.CharField(max_length=45)
    bairro = models.CharField(max_length=45)
    numero = models.IntegerField()
    cidade = models.CharField(max_length=45)
    uf = models.CharField(max_length=2)
    complemento = models.CharField(max_length=45, blank=True, null=True)
    descricao = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'endereco'

cad_enderecos/sys_endereco/forms.py
from django import forms
from django.forms import ModelForm
from sys_endereco.models import Endereco
class cadForm(ModelForm):
    class Meta:
        model = Endereco
        fields = '__all__'

cad_enderecos/sys_endereco/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
# from django.urls import reverse
from sys_endereco.models import Endereco
from sys_endereco.forms import cadForm
from django.core.exceptions import ValidationError
# Create your views here.
def index(request):#Homepage
    addresses = Endereco.objects.values()
    listadd = list(addresses)
    values = []
    for data in listadd:
        values.append(list(data.values()))
    context = {
        'addresses': values,
    }
    return render(request, 'index.html', context=context)

def cadastro(request):#Cadpage
    form = cadForm();
    if request.method == 'POST':
        form = cadForm(request.POST);
        if form.is_valid():
            data_cep = form.cleaned_data['cep']
            data_logr = form.cleaned_data['logradouro']
            data_bai = form.cleaned_data['bairro']
            data_num = form.cleaned_data['numero']
            data_cid = form.cleaned_data['cidade']
            data_uf = form.cleaned_data['uf']
            data_compl = form.cleaned_data['complemento']
            data_desc = form.cleaned_data['descricao']
            temp = Endereco.objects.filter(cep=data_cep)

            new_add = Endereco(cep=data_cep,logradouro=data_logr,bairro=data_bai,
            numero=data_num,cidade=data_cid,uf=data_uf,complemento=data_compl,
            descricao=data_desc)
            new_add.save()
            return redirect('index')
    return render(request, 'cad.html', {'form': form})

cad_enderecos/sys_endereco/templates/cad.html
<!DOCTYPE html>
{% load bootstrap_tags %}
<html lang="pt-br">

<head>
  <title>Cadastrar Endereço</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-10 ">
        <h1>Cadastrar Endereço</h1>
        <form id="form" action="." method="POST">
          {% csrf_token %}
          {{ form|as_bootstrap }}
          <button type="submit" class="btn btn-success">Cadastrar</button>
        </form>
        <script type="text/javascript">
          $("#id_cep").focusout(function() {
            //Início do Comando AJAX
            $.ajax({
              //O campo URL diz o caminho de onde virá os dados
              //É importante concatenar o valor digitado no CEP
              url: 'https://viacep.com.br/ws/' + $(this).val() + '/json/',
              //Aqui você deve preencher o tipo de dados que será lido,
              //no caso, estamos lendo JSON.
              dataType: 'json',
              //SUCESS é referente a função que será executada caso
              //ele consiga ler a fonte de dados com sucesso.
              //O parâmetro dentro da função se refere ao nome da variável
              //que você vai dar para ler esse objeto.
              success: function(resposta) {
                //Agora basta definir os valores que você deseja preencher
                //automaticamente nos campos acima.
                $("#id_logradouro").val(resposta.logradouro);
                $("#id_bairro").val(resposta.bairro);
                $("#id_numero").focus();
                $("#id_cidade").val(resposta.localidade);
                $("#id_uf").val(resposta.uf);
                $("#id_complemento").val(resposta.complemento);
                //Vamos incluir para que o Número seja focado automaticamente
                //melhorando a experiência do usuário
              }
            });
          });
        </script>
      </div>
    </div>
  </div>
</body>

</html>

cad_enderecos/sys_endereco/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <title>Endereços Cadastrados</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-10 ">
        <h1>Endereços Cadastrados</h1>
        <table class="table" border="1">
          <tr>
            <th>CEP</th>
            <th>Logradouro</th>
            <th>Bairro</th>
            <th>Número</th>
            <th>Cidade</th>
            <th>UF</th>
            <th>Complemento</th>
            <th>Descrição</th>
          </tr>
          {% for item in addresses %}
          <tr>
            {% for j in item %}
            <td>{{ j }}</td>
            {% endfor %}
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
    <button onclick="location.href='{% url 'cadastro' %}'" class="bt">Cadastrar</button>
  </div>
</body>

</html>